[package]
name = "xml"
version = "1.0.0"
authors = ["Vladimir Matveev <vmatveev@citrine.cc>", "Kornel (https://github.com/kornelski)"]
license = "MIT"
description = "An XML library in pure Rust"
repository = "https://github.com/kornelski/xml-rs"
homepage = "https://lib.rs/crates/xml-rs"
documentation = "https://docs.rs/xml-rs/"
readme = "README.md"
keywords = ["xml", "parser", "sax", "event-reader", "writer"]
categories = ["parser-implementations"]
edition = "2021"
rust-version = "1.70"
include = ["src/**", "LICENSE", "README.md"]

[lib]
name = "xml"
path = "src/lib.rs"

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--generate-link-to-definition"]

[package.metadata.release]
tag-name = "{{version}}"
tag-message = ""
